// Code generated by MockGen. DO NOT EDIT.
// Source: routers.go

// Package mock_routers is a generated GoMock package.
package mock_routers

import (
        context "context"
        reflect "reflect"

        models "github.com/VanGoghDev/practicum-metrics/internal/domain/models"
        gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
        ctrl     *gomock.Controller
        recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
        mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
        mock := &MockStorage{ctrl: ctrl}
        mock.recorder = &MockStorageMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
        return m.recorder
}

// Close mocks base method.
func (m *MockStorage) Close(ctx context.Context) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Close", ctx)
        ret0, _ := ret[0].(error)
        return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close(ctx interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close), ctx)
}

// Counter mocks base method.
func (m *MockStorage) Counter(ctx context.Context, name string) (models.Counter, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Counter", ctx, name)
        ret0, _ := ret[0].(models.Counter)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Counter indicates an expected call of Counter.
func (mr *MockStorageMockRecorder) Counter(ctx, name interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counter", reflect.TypeOf((*MockStorage)(nil).Counter), ctx, name)
}

// Counters mocks base method.
func (m *MockStorage) Counters(ctx context.Context) ([]models.Counter, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Counters", ctx)
        ret0, _ := ret[0].([]models.Counter)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Counters indicates an expected call of Counters.
func (mr *MockStorageMockRecorder) Counters(ctx interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counters", reflect.TypeOf((*MockStorage)(nil).Counters), ctx)
}

// Gauge mocks base method.
func (m *MockStorage) Gauge(ctx context.Context, name string) (models.Gauge, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Gauge", ctx, name)
        ret0, _ := ret[0].(models.Gauge)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Gauge indicates an expected call of Gauge.
func (mr *MockStorageMockRecorder) Gauge(ctx, name interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockStorage)(nil).Gauge), ctx, name)
}

// Gauges mocks base method.
func (m *MockStorage) Gauges(ctx context.Context) ([]models.Gauge, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Gauges", ctx)
        ret0, _ := ret[0].([]models.Gauge)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Gauges indicates an expected call of Gauges.
func (mr *MockStorageMockRecorder) Gauges(ctx interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauges", reflect.TypeOf((*MockStorage)(nil).Gauges), ctx)
}

// Ping mocks base method.
func (m *MockStorage) Ping(ctx context.Context) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Ping", ctx)
        ret0, _ := ret[0].(error)
        return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorageMockRecorder) Ping(ctx interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorage)(nil).Ping), ctx)
}

// SaveCount mocks base method.
func (m *MockStorage) SaveCount(ctx context.Context, name string, value int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "SaveCount", ctx, name, value)
        ret0, _ := ret[0].(error)
        return ret0
}

// SaveCount indicates an expected call of SaveCount.
func (mr *MockStorageMockRecorder) SaveCount(ctx, name, value interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCount", reflect.TypeOf((*MockStorage)(nil).SaveCount), ctx, name, value)
}

// SaveGauge mocks base method.
func (m *MockStorage) SaveGauge(ctx context.Context, name string, value float64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "SaveGauge", ctx, name, value)
        ret0, _ := ret[0].(error)
        return ret0
}

// SaveGauge indicates an expected call of SaveGauge.
func (mr *MockStorageMockRecorder) SaveGauge(ctx, name, value interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGauge", reflect.TypeOf((*MockStorage)(nil).SaveGauge), ctx, name, value)
}

// SaveMetrics mocks base method.
func (m *MockStorage) SaveMetrics(ctx context.Context, metrics []*models.Metrics) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "SaveMetrics", ctx, metrics)
        ret0, _ := ret[0].(error)
        return ret0
}

// SaveMetrics indicates an expected call of SaveMetrics.
func (mr *MockStorageMockRecorder) SaveMetrics(ctx, metrics interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetrics", reflect.TypeOf((*MockStorage)(nil).SaveMetrics), ctx, metrics)
}