// Code generated by MockGen. DO NOT EDIT.
// Source: filestorage.go

// Package mock_filestorage is a generated GoMock package.
package mock_filestorage

import (
        context "context"
        reflect "reflect"

        models "github.com/VanGoghDev/practicum-metrics/internal/domain/models"
        gomock "github.com/golang/mock/gomock"
)

// MockFilewriter is a mock of Filewriter interface.
type MockFilewriter struct {
        ctrl     *gomock.Controller
        recorder *MockFilewriterMockRecorder
}

// MockFilewriterMockRecorder is the mock recorder for MockFilewriter.
type MockFilewriterMockRecorder struct {
        mock *MockFilewriter
}

// NewMockFilewriter creates a new mock instance.
func NewMockFilewriter(ctrl *gomock.Controller) *MockFilewriter {
        mock := &MockFilewriter{ctrl: ctrl}
        mock.recorder = &MockFilewriterMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilewriter) EXPECT() *MockFilewriterMockRecorder {
        return m.recorder
}

// Close mocks base method.
func (m *MockFilewriter) Close() error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Close")
        ret0, _ := ret[0].(error)
        return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFilewriterMockRecorder) Close() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFilewriter)(nil).Close))
}

// FileIsNil mocks base method.
func (m *MockFilewriter) FileIsNil() bool {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FileIsNil")
        ret0, _ := ret[0].(bool)
        return ret0
}

// FileIsNil indicates an expected call of FileIsNil.
func (mr *MockFilewriterMockRecorder) FileIsNil() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileIsNil", reflect.TypeOf((*MockFilewriter)(nil).FileIsNil))
}

// ReadMetrics mocks base method.
func (m *MockFilewriter) ReadMetrics() ([]*models.Metrics, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadMetrics")
        ret0, _ := ret[0].([]*models.Metrics)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ReadMetrics indicates an expected call of ReadMetrics.
func (mr *MockFilewriterMockRecorder) ReadMetrics() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMetrics", reflect.TypeOf((*MockFilewriter)(nil).ReadMetrics))
}

// SaveMetrics mocks base method.
func (m *MockFilewriter) SaveMetrics(ctx context.Context, data []byte) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "SaveMetrics", ctx, data)
        ret0, _ := ret[0].(error)
        return ret0
}

// SaveMetrics indicates an expected call of SaveMetrics.
func (mr *MockFilewriterMockRecorder) SaveMetrics(ctx, data interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetrics", reflect.TypeOf((*MockFilewriter)(nil).SaveMetrics), ctx, data)
}