// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go

// Package mock_config is a generated GoMock package.
package mock_config

import (
        reflect "reflect"

        config "github.com/VanGoghDev/practicum-metrics/internal/agent/config"
        gomock "github.com/golang/mock/gomock"
)

// MockEnvironmentReader is a mock of EnvironmentReader interface.
type MockEnvironmentReader struct {
        ctrl     *gomock.Controller
        recorder *MockEnvironmentReaderMockRecorder
}

// MockEnvironmentReaderMockRecorder is the mock recorder for MockEnvironmentReader.
type MockEnvironmentReaderMockRecorder struct {
        mock *MockEnvironmentReader
}

// NewMockEnvironmentReader creates a new mock instance.
func NewMockEnvironmentReader(ctrl *gomock.Controller) *MockEnvironmentReader {
        mock := &MockEnvironmentReader{ctrl: ctrl}
        mock.recorder = &MockEnvironmentReaderMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironmentReader) EXPECT() *MockEnvironmentReaderMockRecorder {
        return m.recorder
}

// ReadEnvironment mocks base method.
func (m *MockEnvironmentReader) ReadEnvironment(cfg *config.Config) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadEnvironment", cfg)
        ret0, _ := ret[0].(error)
        return ret0
}

// ReadEnvironment indicates an expected call of ReadEnvironment.
func (mr *MockEnvironmentReaderMockRecorder) ReadEnvironment(cfg interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEnvironment", reflect.TypeOf((*MockEnvironmentReader)(nil).ReadEnvironment), cfg)
}

// MockFlagsReader is a mock of FlagsReader interface.
type MockFlagsReader struct {
        ctrl     *gomock.Controller
        recorder *MockFlagsReaderMockRecorder
}

// MockFlagsReaderMockRecorder is the mock recorder for MockFlagsReader.
type MockFlagsReaderMockRecorder struct {
        mock *MockFlagsReader
}

// NewMockFlagsReader creates a new mock instance.
func NewMockFlagsReader(ctrl *gomock.Controller) *MockFlagsReader {
        mock := &MockFlagsReader{ctrl: ctrl}
        mock.recorder = &MockFlagsReaderMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlagsReader) EXPECT() *MockFlagsReaderMockRecorder {
        return m.recorder
}

// ReadFlags mocks base method.
func (m *MockFlagsReader) ReadFlags(cfg *config.Config) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadFlags", cfg)
        ret0, _ := ret[0].(error)
        return ret0
}

// ReadFlags indicates an expected call of ReadFlags.
func (mr *MockFlagsReaderMockRecorder) ReadFlags(cfg interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFlags", reflect.TypeOf((*MockFlagsReader)(nil).ReadFlags), cfg)
}